
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  engine: "classic",
  datasource: {
    // Use DATABASE_URL if available, otherwise use a placeholder for prisma generate
    url: process.env.DATABASE_URL || process.env.TURSO_DATABASE_URL || "file:./dev.db",
  },
});
